### PR TITLE
creates threads for queues. 

### PR DESCRIPTION
**Pull request by dethorpe**
Functions still need to do processing for random amounts of time. But wanted to have this part on master before I started a new inst of random.

### CODE REVIEW

**Comment by siebenluke** [comment]
I also tried adding some stuff for the threads if you want to check out my branch before merging.

**Comment by dethorpe** [comment]
huh. I am not 100% clear but it looks like we are pulling in two different directions. And I didn't notice the process**_QUEUE threads down there.

Working in **Tread() my methods have implement a mutex for each queue array and counter. I've been working on the logic of section preference vs timeout vs impatience.

But I'm sticking closely to the professor's examples and how I understand them.

**Comment by dethorpe** [comment]
Since we both are working on different implementations in discrete functions I don't see any conflicts. Maybe a waste of time but I don't see what else to re-task to.

**Comment by siebenluke** [comment]
Since you've already added in mutexs and stuff let's go ahead and use yours.

**Pull request merged**
